name: Nightly Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  nightly-build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed for GitHub Releases
      actions: write   # Needed for uploading artifacts

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y wget

      - name: Run the build script
        run: |
          bash build.sh
          python3 card/card_creator.py

      - name: Update the nightly release
        uses: softprops/action-gh-release@v1
        with:
          files: [MULTIROM-512KiB.BIN, card.png]
          tag_name: nightly
          release_name: Nightly Build
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-card:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install -y python3 python3-pil
    - uses: actions/checkout@v3
    - name: Build card
      run: |
        python3 roms/card/card_creator.py
        mv card.png multirom-card.png
    - name: Upload card
      uses: actions/upload-artifact@v4
      with:
        name: multirom-card.png
        path: multirom-card.png